### PR TITLE
Documentation update (formatting, descriptions)

### PR DESCRIPTION
**Pull request by Gradous**
Hi,

I've done my best to add field descriptions to each of the responses. I also styled all responses as  code blocks (sort of looks like a dictionary layout), which will hopefully save some page space and scrolling.

There are some status variables that I didn't know what to put, I'll probably find out what those mean as I work more with the API. Doing documentation was my way of getting to know the feature set.

I renamed the files to `.rst` instead of `.txt` since it was more convenient to get restructuredText formatting in Sublime that way. Some people don't like that, but considering that it's the extension most editors will recognize, I think it should be OK. I'm not sure how PyCharm will interact with it.

There were some binary files that were uploaded as well, I believe I added something to the `.gitignore` that should keep those from being uploaded. I also think I prevented the HTML I was generating from getting to the repo as well.

I didn't want to just create a new readthedocs site for testing how the formatting looked, but that may be worthwhile.

Thanks!

### CODE REVIEW

**Comment by Gradous** [comment]
You may want to check out the Travis CI conditions as well, I didn't do any changes to the Python but it complains about environment variables. Or is that something I missed?

**Comment by joshuaduffy** [comment]
Pull requests cannot use environment variables (which the api key is stored in) so ignore the failures. This is much appreciated! I will get this merged in and the documentation updated.

**Comment by Gradous** [comment]
It looks like there are still some fields that aren't included, do you want separate pull requests for those?

For example, `get_live_league_games()` doesn't have the `stream_delay_s` field listed in the documentation (anywhere else either...)

**Comment by joshuaduffy** [comment]
Looks like valve has added some more fields to the API :smile: if you spot any feel free to raise a pull request! New pull request is fine!

**Comment by joshuaduffy** [comment]
Merged and closed. Thank you @Gradous for your efforts on this. Much appreciated!

**Pull request merged**
