### PR TITLE
Api enhancements

### PR DESCRIPTION
**Pull request by evaldobratti**
Since object branch was dropped, I have been working to bring some features I have developed there.
- Automatically converts ids in ```get_player_summaries```
- Leaver status descriptions
- Urls images for items and heroes

### CODE REVIEW

**Comment by joshuaduffy** [comment]
Hey, cheers for this. Will take a look at the failures and get this merged in ASAP. Happy with all the changes :)

**Comment by evaldobratti** [comment]
I executed tests locally, and all passed.
The problem is that some tests that access valve api directly, and it turns intermitent due to errors returned by that :(

**Comment by joshuaduffy** [comment]
I know, integration tests are a pain... The rate limiter seems to work (or work better?) now. I only have one API key that I use locally and on the CI build.

Trying to fix the build now, then will merge this, looks great to me, cheers!

**Comment by joshuaduffy** [comment]
For some reason, you can't use the environment variables in builds triggered by a pull request. Tests run fine on my machine, lets see what Travis says in `main` :)

**Pull request merged**
