### PR TITLE
Object response

### PR DESCRIPTION
**Pull request by evaldobratti**
You can see the result at integration_test.
I improved the Item and Hero results to contains their respective urls and it now converts the steamid parameters if they are not converted.
The objects are basically the same as the previous dictionaries, with some better typos

### CODE REVIEW

**Comment by joshuaduffy** [comment]
Hey Evaldo,

This looks really great, thanks for all your work on this!

Before merging into master, I would like to update the documentation and parse the abilities which I can do this week? Lets look at getting this merged by the end of the month?

Any thoughts?

Again thank you for all your hard work on this!

Thanks,
Josh

**Comment by joshuaduffy** [comment]
Do you know if the fix to heroku will also fix the dependency issues with `pip install`?

Thanks,
Josh

**Comment by evaldobratti** [comment]
Yeah, the problem was the api on __init__ file. Since setup.py references dota2api.__version__, etc, and it was referencing requests due to api, the whole setup would fail.

**Comment by evaldobratti** [comment]
just noticed that docs uses .rst files as source, is there any problem that I changed our readme to .md?

**Comment by joshuaduffy** [comment]
Great find, quite a simple fix then but hardcoding the version in `setup.py`

PyPi only displays `*.rst` files on the package description, don't worry about it, I can convert!

Thanks,
Josh

**Comment by evaldobratti** [comment]
I have serious problems with layouts, I really don't know how to make things look well. Do you think we could merge this?
We can create the proper tags when the docs and other things are done

**Comment by joshuaduffy** [comment]
What's that sorry, the layouts for the documents/rst files? They are quite tricky to get used to so don't worry!

I would really like to have a look first beforehand! The document updates shouldn't take me too long either!

Thanks,
Josh

**Comment by joshuaduffy** [comment]
Apologies for the late reply.
I am all up for this been v2.0 but I want to update the documentation first!

**Comment by Norgat** [comment]
I think that using objects for teams, players and so on it's not good idea.
Why? Because users can use own objects system and don't wanted to use this objects.
But you waste time to convert dicts to objects.

For example, I store responses dicts to MongoDB and I realy don't want to get objects from library.
I think that library must return only pure dicts and users convert dicts to what they want.

**Comment by evaldobratti** [comment]
Yeah, I started to think that way after I developed and really started using the api on my own project.

I'll start to bring some improvements I have developed on this branch to master, but the response will continue to be dicts.

Thank you for your testimonial

**Comment by joshuaduffy** [comment]
Thanks guys. I really want to find a way so we can have both. My main
concern is with breaking backwards compatibility if someone `pip install
dota2api --upgrade`

Thanks,
Josh

**Pull request closed without merging**
